project:
  type: book
  output-dir: docs
  resources: lectureslides.pdf



book:
  title: "MA32009"
  author: "Philip Murray"
  date: "12/22/2023"
  repo-url: https://github.com/dundeemath/MA32009/
  downloads: pdf
  repo-actions: [issue]
  cover-image: MA32009Cover.png


  
  chapters:
    - index.qmd
    - part: "Discrete time"
      chapters: 
        - DiscreteTimeOnePop.qmd
        - DiscreteTimeTwoPop.qmd
    - part: "Continuous time"
      chapters:
        - CtsTimeOnePop.qmd
        - CtsTimeMultiPop.qmd  
        - Biochemicalkinetics.qmd

    - part: "Appendices"
      chapters:
        - PythonAppendix.qmd    
        - CurveSketching.qmd
        - QuizReview.qmd
      
bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
  pdf:
    documentclass: scrreprt
    echo: false
    include-in-header:
      - text: |
          \usepackage{chemarr}
          \usepackage{lipsum}
          \usepackage{tikz}
          \AtBeginDocument{\thispagestyle{empty}
          \begin{tikzpicture}[remember picture,overlay]
          \node at (current page.center) {\includegraphics[width=\paperwidth,height=\paperheight,keepaspectratio]{MA32009Cover.png}};
          \end{tikzpicture}\clearpage}

execute:
  warning: false
     


  



