project:
  type: book

book:
  title: "MA32009"
  author: "Philip Murray"
  date: "12/22/2023"
  repo-url: https://github.com/dundeemath/MA32009/
  downloads: pdf

  chapters:
    - index.qmd
    - part: "Discrete time"
      chapters: 
        - MA32009-SinglePopDiscreteTimea.qmd
        - DiscreteModels2d.qmd
    - part: "Continuous time"
      chapters:
        - SinglePopODEMOdels.qmd
        - ContinuousTimeTwoSepcies.qmd  
        - enzymekinetics.qmd
      
bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
  pdf:
    documentclass: scrreprt
    echo: false



