# Preface {.unnumbered}


Welcome to MA32009 Mathematical Biology I.

My name is Philip Murray and I am the module lead.

## How to contact me?

* email: pmurray@dundee.ac.uk
* office: G11, Fulton Building
* Teams: PM me


## Lecture notes
You can find lecture notes for the module on this page. If you would like a pdf this can be easily generated by clicking on the pdf link of the  webpage. I will occasionally edit/update the notes as we proceed through lectures. If you spot any errors, typos or omissions please Raise an Issue

## Reading 
Mathematical Biology I, @murray2002mathematical

Esswential Mathemtical Biology @britton2003essential

Mathematical models in Biology @edelstein2005mathematical

## Python codes

I have provided Python codes for most of the figures in the notes (you can unfold code section by clicking `Code'). Note that the Python code does not appear in the pdf.

 Many of you have taken the Introduction to Programming module at Level 2 and have therefore some experience using Python. I strongly encourage you to use the provided codes as a tool to play around with numerical solutions of the various models that we will be working on. The codes should run as standalone Python codes.

 I have also provided some examples of how to use Python as a symbolic calculator. This uses a Python library called *sympy* and is quite similar to Maple. 

## Assessment
 
* Final exam (80 \%)

* 2 class tests (8.5 \% each), Week 6 and 10

* 3 quizes (1 \% each), Week 2,4 and 8

## Plan

| Week | Up to Section | Tutorial sheet|
|-------|:---|-----|
| 1     | 1.4  |   1 |
| 2     | 1.6  |   1 |
| 3     | 2  |   2 |
| 4     | 2  |   2 |
| 5     | 3  |   3 |
| 6     | 3  |   3 |
| 7     | 4  |   4 |
| 8     | 4  |   4 |
| 9     | 4  |   5 |
| 10    | 5  |   5 |
| 11    | 5  |    |
: Projected delivery

## References
